---
abstract: 'oauth2 authentication library'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires:
  Mojolicious: '0'
  Pod::Elemental::Transformer::List: '0'
  Pod::Weaver::Section::WarrantyDisclaimer: '0'
  Test::Mojo: '0'
  Test::More: '0'
  Test::NoTabs: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.017, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-PayPal
requires:
  DDP: '0'
  Mojo::Base: '0'
  Mojo::Parameters: '0'
  Mojo::URL: '0'
  Mojo::UserAgent: '0'
version: '1.0'
